# Joint position bounds (defined as fraction of pi)
q_min: -0.25
q_max: 0.25
# Joint velocity bounds
dq_min: -10
dq_max: 10
# Joint torque bounds
tau_min: -0.8
tau_max: 0.8
# State bounds tolerance
state_tol: 1e-2